export declare enum Token {
    Package = 1,
    Record = 2,
    Property = 3,
    Import = 4,
    ImportType = 5,
    BuildinType = 6,
    OptionalType = 7,
    RepeatedType = 8,
    MapType = 9,
    Annotation = 10,
}
export declare enum Modifier {
    Optional = 0,
    Repeated = 1,
    Annotation = 2,
}
export declare enum Type {
    String = 1,
    Date = 2,
    Int8 = 3,
    Int16 = 4,
    Int32 = 5,
    Int64 = 6,
    Double = 7,
    Float = 8,
    Uint8 = 9,
    Uint16 = 10,
    Uint32 = 11,
    Uint64 = 12,
    Boolean = 13,
    Int = 14,
    Uint = 15,
    Bytes = 16,
}
